export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  FAQS: '/faqs',
  HOW_IT_WORKS: '/how-it-works',
  MARKETPLACE: '/marketplace',
  RESOURCES: '/resources',
  INSIGHTS: '/insights',
  HELP_CENTER: '/help-center',
  RESOURCES_ARTICLE: '/resources/articles/:slug',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS: '/terms',
  LICENSES: '/licenses',
  CAREERS: '/careers',
  PRESS: '/press',
  ADVISORY: '/advisory',
  PARTNERSHIPS: '/partnerships',
  NOT_FOUND: '/404'
} as const;